apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidssokerregistrering-veileder
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
      replyURLs:
        - "https://arbeid.dev.intern.nav.no/arbeid/arbeidssokerregistrering-veileder/api/auth/callback/oauth2"
        - "http://localhost:3000/arbeid/arbeidssokerregistrering-veileder/api/auth/callback/oauth2"
  liveness:
    path: /arbeid/arbeidssokerregistrering-veileder/isAlive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /arbeid/arbeidssokerregistrering-veileder/isReady
    timeout: 1
  ingresses:
    - "https://arbeid.dev.intern.nav.no/arbeid/arbeidssokerregistrering-veileder"
  accessPolicy:
    inbound:
      rules:
        - application: arbeid.dev.intern.nav.no
    outbound:
      rules:
        - application: arbeid.dev.intern.nav.no
      external:
        - host: internarbeidsflatedecorator.nais.adeo.no
        - host: login.microsoftonline.com
        - host: veilarbregistrering-q1.dev.adeo.no
        - host: veilarbproxy.q1.svc.nais.local
        - host: arbeid.dev.intern.nav.no