apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidssokerregistrering-veileder
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /isAlive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isReady
    timeout: 1
  ingresses:
    - "https://arbeid.dev.adeo.no/arbeid/arbeidssokerregistrering-veileder"
    - "https://arbeid.dev.nav.no/arbeid/arbeidssokerregistrering-veileder"
  #accessPolicy:
  #  outbound:
  #    external:
  #      - host: https://veilarbregistrering-q1.nais.preprod.local